FROM phpdockerio/php:8.2-fpm
WORKDIR "/application"

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        php8.2-bcmath \ 
        php8.2-decimal \ 
        php8.2-gd \ 
        php8.2-gearman \ 
        php8.2-grpc \ 
        php8.2-http \ 
        php8.2-intl \ 
        php8.2-mysql \ 
        php8.2-redis \ 
        php8.2-uuid \ 
        php8.2-xdebug \ 
        php8.2-xmlrpc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
